version: '3.8'

services:
  api:
    image: minhaaplicacao_api
    build:
      context: ./src/MinhaAplicacao.Api
      dockerfile: ../../Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=MinhaAplicacaoDb;User Id=sa;Password=Your_password123; 
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      - SA_PASSWORD=Your_password123
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - db_data:/var/opt/mssql

volumes:
  db_data: